language: go
go:
  - 1.10.x

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:maarten-fonville/protobuf'

notifications:
  email: false

env:
  global:
    - MKL_DNN_VER: "0.16"
    - MENOH_VER: "1.1.1"

before_install:
  - |
    sudo apt update
    curl -LO https://github.com/pfnet-research/menoh/releases/download/v${MENOH_VER}/ubuntu1404_mkl-dnn_${MKL_DNN_VER}-1_amd64.deb
    curl -LO https://github.com/pfnet-research/menoh/releases/download/v${MENOH_VER}/ubuntu1404_menoh_${MENOH_VER}-1_amd64.deb
    curl -LO https://github.com/pfnet-research/menoh/releases/download/v${MENOH_VER}/ubuntu1404_menoh-dev_${MENOH_VER}-1_amd64.deb
    sudo dpkg -i --force-depends *.deb
    sudo apt install -f
  - export CPATH=/usr/include:$CPATH
  - export LIBRARY_PATH=/usr/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
  # Test tool
  - go get -u golang.org/x/lint/golint

install:
  - go get -t -d -v ./...
  - go build -v ./...

script:
  - go vet ./...
  - golint -set_exit_status ./...
  - wget https://github.com/pfnet-research/menoh-rs/releases/download/assets/MLP.onnx -P test_data
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
